import { Card, Button, Form, FormItem, Input, Menu, MenuItem, Submenu, Main, Aside, Container, Header, Breadcrumb, BreadcrumbItem, Row, Col, Table, TableColumn, Pagination, Dialog, Select, Switch, Tooltip, Option, Tree, Tag, Alert, Steps, Step, Tabs, TabPane, Cascader, Upload, CheckboxGroup, Checkbox, Timeline, TimelineItem } from 'element-ui'
const element = {
  install: function (Vue) {
    Vue.use(Card)
    Vue.use(Button)
    Vue.use(Form)
    Vue.use(FormItem)
    Vue.use(Input)
    Vue.use(Menu)
    Vue.use(MenuItem)
    Vue.use(Submenu)
    Vue.use(Main)
    Vue.use(Aside)
    Vue.use(Container)
    Vue.use(Header)
    Vue.use(Breadcrumb)
    Vue.use(BreadcrumbItem)
    Vue.use(Row)
    Vue.use(Col)
    Vue.use(Table)
    Vue.use(TableColumn)
    Vue.use(Pagination)
    Vue.use(Dialog)
    Vue.use(Select)
    Vue.use(Switch)
    Vue.use(Tooltip)
    Vue.use(Option)
    Vue.use(Tree)
    Vue.use(Tag)
    Vue.use(Alert)
    Vue.use(Steps)
    Vue.use(Step)
    Vue.use(Tabs)
    Vue.use(TabPane)
    Vue.use(Cascader)
    Vue.use(Upload)
    Vue.use(CheckboxGroup)
    Vue.use(Checkbox)
    Vue.use(Timeline)
    Vue.use(TimelineItem)
  }
}

export default element
